# Generated by Django 4.0.4 on 2022-05-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sound',
            old_name='audio',
            new_name='audio_file',
        ),
        migrations.AddField(
            model_name='sound',
            name='audio_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
